### PR TITLE
Fix fractional seconds support, for mysql 5.6.4+

### PR DESCRIPTION
**Pull request by locene**

### CODE REVIEW

**Comment by steveschmitt** [comment]
Should the datatype be `DataTypes.DATE6` or `DataTypes.DATE(6)` ?

**Comment by locene** [comment]
> Should the datatype be `DataTypes.DATE6` or `DataTypes.DATE(6)` ?

DataTypes.DATE(6)
https://sequelize.org/master/manual/model-basics.html#dates

**Comment by steveschmitt** [comment]
Ok, can you update your PR to include the parentheses?

**Comment by locene** [comment]
> Ok, can you update your PR to include the parentheses?

No need, the variable 'length' has already included the parentheses, look at this line of code:
https://github.com/sequelize/sequelize-auto/blob/b46bc9e9113e034ea9810853ae621560cd4a9f20/src/auto-generator.ts#L341

**Comment by steveschmitt** [comment]
Aha!  I missed that.  Thanks!

**Pull request merged**
