### PR TITLE
Feat: allow password to be supplied from terminal

### LINKED ISSUE #351: read password from console?
Many CLI applications have the option to run with the password switch but without providing any value, and then prompts for the password with echo turned off (i.e. you cannot see the password on screen). For example:
```console
$ mysql -h host -P 3306 -u user -p
Enter password:
^C
$ mysql -h host -P 3306 -u user -p=password
mysql: [Warning] Using a password on the command line interface can be insecure.
```

This can prevent leaving the password in shell history e.g. `~/.bash_history`. But it seems like sequelize-auto does not support this at the moment?

### PR DESCRIPTION
**Pull request by zypA13510**
There're quite a lot of things in here, but the later ones probably depend on the ones before so I created this one PR for them. I hope you don't mind.

1. Added the ability to read password from terminal. Closes #351. Also prevent password from printing back to terminal.
1. Fixed the inconsistent priority between CLI parameters and config file. Now CLI parameters always trump config file.
    **BREAKING CHANGE**: obviously, anyone depending on config file to take over CLI parameters will now have to update their configuration. (But it should be rare, who will spend the extra time to type CLI parameters just for it to be overridden by something already on disk, right?)
1. Refactored code to use yargs to parse `tables` (-t) and `skipTables` (-T) option.
    **BREAKING CHANGE**: `tables` (-t) and `skipTables` (-T) option are now space-separated (was comma-separated).
1. Better help output by upgrading yargs to next major (v16). 
    **BREAKING CHANGE**: drop support of node < 10.

### CODE REVIEW

**Comment by steveschmitt** [comment]
Thanks!  I'll get this merged in.

**Comment by steveschmitt** [comment]
Merged!  Thanks again for your work on this.

**Comment by zypA13510** [comment]
Btw @steveschmitt, while working on this, I discovered that yargs has built-in handling for config files: [.config()](https://github.com/yargs/yargs/blob/master/docs/api.md#configkey-description-parsefn). However, I reckoned I have introduced enough breaking change in this already, so I didn't go into the details. But I guess it's worth mentioning. Maybe you would be interested in doing that in a future release.

**Comment by steveschmitt** [comment]
Included this PR in release 0.8.1

I'll look into the yargs `.config` option some other time.

Thanks again.

**Pull request merged**
