### PR TITLE
Implement generating hasTrigger (#217)

### PR DESCRIPTION
**Pull request by joaoe**
I piled some of my changes in this branch: proper schema support, triggers and fixing a couple bugs. I recommend you review each commit separately as the git history is clean. If you merge, please don't squash.

Git log:

---

**mssql: ignore check constraints when gathering foreign key info**

The check constraints would overwrite the foreign key info.

issue #381

---

**Implement generating hasTrigger flag for auto-generated models (#217)**

---

**Finalize database schema support**

Now database schema are supported across all DB dialect which support schemas
(currently only sqlite does not upport them).

Fixes both #348 and bug #354 as a bonus.

---

**Small fixes**

* Missing comma after autoIncrement
* Don't output empty comments
* Call error callacks in two extra places
* Use multiline string in dialects.js like all other strings and fix indentation.

---

**Assorted stability changes in unit tests**

Most changes were about making sure that the done() method is called and that
self is perserved across function calls

---

**Stripped trailing whitespace**

### CODE REVIEW

**Comment by steveschmitt** [comment]
This is great work!

I've just released `sequelize-auto@0.5.0` with a lot of small changes, but I didn't include this PR.  I will try to get it into the next release.  There are a lot of conflicts right now; do you think you can re-base your PR on the current `master` branch?

Thanks for your work on this.

**Comment by joaoe** [comment]
Hi.
I'm glad to see this finally coming alive :)
Sure I'll rebase and try again. Might take a couple days until I'm ready to update the PR.
Cheers.

**Comment by joaoe** [comment]
@steveschmitt Question: which is the lowest sqlite version that is supported ?
In one of the commit I fixup schema support, but the code can be improved further by using pragma functions in sqlite and abstracting away differences from the main shared code. But that feature is available since sqlite 3.16.0 which is 3 years old 
https://www.sqlite.org/releaselog/3_16_0.html

**Comment by steveschmitt** [comment]
> Question: which is the lowest sqlite version that is supported ?

I think we need to support older versions, so I wouldn't rely on the **pragma** functions.

**Comment by joaoe** [comment]
@steveschmitt It's rebased and pushed :)
So far I tested in MSSQL and SQLite.
The CI pipeline is broken.
If you can test in mysql and postgres that would be awesome, else I need to setup my linux environment. Haven't used it the last year...

**Comment by steveschmitt** [comment]
I found and fixed a couple of minor problems in testing mysql and postgres.  I think schema support is still not 100% in mysql, but your changes have shown the way.
Fixing the CI pipeline is on my list of things to do, but I'd rather fix bugs in the actual product!

Thanks again for your work on this.

**Comment by joaoe** [comment]
Hi. Awesome ! Thank you for merging, I had lost hope about this project. Glad I could help :) 

Schema support in mysql might be shaky. I remember not so long ago seeing the discussion in the main sequelize project, because mysql mixes SCHEMA with DATABASE semantics, so it was not clear what should schema represent in sequelize.

But at least I think schema support now works on postgress, and I'm using MSSQL in my project so that works at least as far as I've tested.

Cheers.

**Pull request merged**
