### PR TITLE
fix: changed generation alias for many-to-many

### PR DESCRIPTION
**Pull request by IlyaIvanchikov**

### CODE REVIEW

**Comment by steveschmitt** [comment]
Thanks!

**Comment by IlyaIvanchikov** [comment]
> Thanks!

Can you tell me, when to wait for the release?

**Comment by steveschmitt** [comment]
Probably 2 more days.  There are some other things that I want to include.

**Comment by IlyaIvanchikov** [comment]
> Probably 2 more days. There are some other things that I want to include.

Thanks!

**Pull request merged**
