### PR TITLE
merge to master

### PR DESCRIPTION
**Pull request by sschwenker**

### CODE REVIEW

**Comment by sschwenker** [comment]
Sorry.  I configured this the wrong way.

**Comment by sschwenker** [comment]
Please delete pull request.

**Comment by steveschmitt** [comment]
Yeah, I think you need to checkout master and start over with your changes.

**Comment by sschwenker** [comment]
Hey Steve. I tried your code gen and it doesn't compile for typescript. Thank you for integrating my previous branch, but I still cant use it.
Sent from Yahoo Mail on Android 
 
  On Wed., 7 Oct. 2020 at 19:14, Steve Schmitt<notifications@github.com> wrote:   


Yeah, I think you need to checkout master and start over with your changes.

**Comment by steveschmitt** [comment]
Yeah, I've discovered a few problems.  Working on it now.

**Comment by steveschmitt** [comment]
Please try the latest 0.6.4 version.

**Pull request closed without merging**
