### PR TITLE
Ignore timestamps

### PR DESCRIPTION
**Pull request by cedrouck**
Use to ignore generation of createdAt updatedAt and deletedAt, because sequelize create it automatically if we set timestamps=true in sequelize model definition

### CODE REVIEW

**Comment by durango** [comment]
Why was this closed?

**Comment by x3r10n** [comment]
Can we reopen this ? It would be a useful flag.

**Comment by cedrouck** [comment]
Hi, flag is already here.

```
var auto = new SequelizeAuto('database', 'user', 'pass', {
    host: 'localhost',
    dialect: 'mysql'|'mariadb'|'sqlite'|'postgres'|'mssql',
    directory: false, // prevents the program from writing to disk
    port: 'port',
    additional: {
        timestamps: false <---------- Flag
        //...
    },
    tables: ['table1', 'table2', 'table3']
    //...
})
```

**Comment by TooBug** [comment]
Any update on this? Or any alternative method on this?

**Pull request closed without merging**
