### PR TITLE
Implement typescript generation

### PR DESCRIPTION
**Pull request by sschwenker**
Hey guys,

I've implemented a generator that generate more complete typescript.  It's not perfect but I will be expanding on the implementation more.  Here is a sample of the outputted typescript.

```
/* jshint indent: 2 */

import { Model, DataTypes } from 'sequelize';

interface TestTableAttributes {
  id?: number
  Name?: string
  enabled?: boolean
}

export default class TestTable extends Model<TestTableAttributes, any>
  implements TestTableAttributes {
  public id?: number

  public Name?: string

  public enabled?: boolean

  static initModel(sequelize) {
    TestTable.init({
      id: {
        autoIncrement: true,
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true,
      },
      Name: {
        type: DataTypes.STRING(50),
        allowNull: true,
      },
      enabled: {
        type: DataTypes.BOOLEAN,
        allowNull: true,
      },
    }, {
      sequelize,
      tableName: 'TestTable',
      schema: 'dbo',
      timestamps: false,
    });
    return TestTable;
  }
}
```

Thank you,

Steve

### CODE REVIEW

**Comment by steveschmitt** [comment]
Very cool!  TypeScript support has been lacking, so it's great to see this.  Thanks!

Is there an opportunity for more code re-use between the JS and TS generators?

**Comment by sschwenker** [comment]
I'm sure there's an opportunity for more code re-use.  That just wasn't my priority at the moment and my next task is to attempt auto-generation of relation methods(getters, setters, ...).

**Comment by steveschmitt** [comment]
I'm just concerned about the two diverging.  We want the same features/fixes in both.  The generated `init` methods should be the same.

**Comment by steveschmitt** [comment]
I'm working on refactoring the generators now.

**Pull request merged**
