### PR TITLE
MSSQL Support for schema

### PR DESCRIPTION
**Pull request by dlredden**
This PR address both #348 and #349

The primary item addressed was #348 and that implicitly addressed #349. I've included tests for MSSQL and gave it a pretty thorough beating. You'll notice a few other things I "cleaned" up relating to code formatting and replacing var with let/const in the test scripts.

The biggest change I made that feels dirty is line 54 of `lib/index.js` where I'm injecting the schema to the tables[table] object in the same way column objects are added. So, __schemaName__ could be confused with a column if it were not handled well. I have code to grab the value and delete it before the columns are processed. I wanted to call this out because it's a hacky solution and there are a few better ways to deal with the existence of a schema but I didn't want to introduce anything too cumbersome and this seemed simple enough to slip into place.

My team and I are open to helping maintain this library from a MSSQL perspective if that's of any help.

### CODE REVIEW

**Comment by dlredden** [comment]
I'll work on spinning up MySQL, Postgres, and SQLite environments and getting the tests to run. I'll also back out the yarn.lock commit.

**Comment by steveschmitt** [comment]
This is great work!

I've just released `sequelize-auto@0.5.0` with a lot of small changes, but I didn't include this PR.  I will try to get it into the next release.  There are a lot of conflicts right now; do you think you can re-base your PR on the current `master` branch?

Thanks for your work on this.

**Comment by joaoe** [comment]
After the work in https://github.com/sequelize/sequelize-auto/pull/374 this PR is mostly obsolete.
There is still value in the extra unit tests, but they should be adjusted to run in all dbs that support schemas, not only mssql.

**Comment by steveschmitt** [comment]
Thanks again.  Your changes are incorporated in `sequelize-auto@0.5.1`

**Comment by dlredden** [comment]
I just now saw your comments to me. Sorry for not being more helpful. I'm really happy to see this repo getting some love.

**Pull request closed without merging**
