### PR TITLE
fixing issue #416 - handling case sensitive collation in MSSQL

### PR DESCRIPTION
**Pull request by karpikpl**
This should fix issue #416

### CODE REVIEW

**Comment by karpikpl** [comment]
I'm getting an error when I try to run test locally with SQL server 2019
```
[MSSQL] sequelize-auto generate
  sequelize-auto:generate-tests Creating tables to run tests against. +0ms
(node:33598) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: Invalid object name 'information_schema.schemata'.
```
could someone help with running the tests locally?

**Comment by karpikpl** [comment]
> I'm getting an error when I try to run test locally with SQL server 2019
> 
> ```
> 
> [MSSQL] sequelize-auto generate
> 
>   sequelize-auto:generate-tests Creating tables to run tests against. +0ms
> 
> (node:33598) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: Invalid object name 'information_schema.schemata'.
> 
> ```
> 
> could someone help with running the tests locally? 

I was able to figure it out and tests passed on SQL 2019

**Comment by steveschmitt** [comment]
Thanks!  I'll get to this soon.

**Comment by steveschmitt** [comment]
Merged manally.  Thanks for this!

**Pull request closed without merging**
